### ISSUE TITLE
Hola

### ISSUE THREAD

**Issue by livrasand** [saulotarsobc/jw-sc#14]
¿Eres Testigo de Jehová? Tengo un proyecto en curso, su nombre secreto es Wasserstoff, es un software para siervos ministeriales, ancianos y superintendentes de circuito, desarrollado en Electron. ¿Te gustaría apoyar nuestro proyecto?

**Comment by saulotarsobc** [comment]
Sou. Meu irmão. Diga como posso ajudar?
